Repository InFrame-dev/InFrame-iOS, pull requests merged in 2021-09, with the labels that each got.

#57 README 작성
  README.md
  READMEData/FORES-Logo.svg
  READMEData/InFrame-LogoImage.svg
Labels: complete, urgent, code-review

#58 README
  README.md
  READMEData/FORES-Logo.svg
  READMEData/InFrame-LogoImage.svg
Labels: complete

#63 이미지, 라벨 추가
  InFrame/Assets.xcassets/InFrame_Logo.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_Logo.imageset/Group 444.png
  InFrame/Resources/Base.lproj/LaunchScreen.storyboard
  Podfile.lock
Labels: complete

#66 폰트 오류 해결
  InFrame/Info.plist
Labels: hotfix, urgent

#68 폰트 적용
  InFrame/Controllers/LoginViewController.swift
Labels: complete

#69 Feature/sign up
  InFrame.xcodeproj/project.pbxproj
  InFrame/Controllers/LoginViewController.swift
  InFrame/Controllers/SignUpViewController.swift
  InFrame/Resources/SceneDelegate.swift
Labels: complete, code-review

#70 Develop
  InFrame.xcodeproj/project.pbxproj
  InFrame/Assets.xcassets/InFrame_Eye.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_Eye.imageset/숨기기EZY_eye.svg
  InFrame/Assets.xcassets/InFrame_EyeNo.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_EyeNo.imageset/EYEYEYEYEYEY.svg
  InFrame/Controllers/LoginViewController.swift
  InFrame/Controllers/SignUpViewController.swift
  InFrame/Info.plist
  InFrame/Resources/SceneDelegate.swift
Labels: complete

#71 Feature/terms of service
  InFrame.xcodeproj/project.pbxproj
  InFrame/Assets.xcassets/InFrame_Arrow.imageset/<<<.svg
  InFrame/Assets.xcassets/InFrame_Arrow.imageset/Contents.json
  InFrame/Controllers/AgreeButton.swift
  InFrame/Controllers/TermsOfServiceViewController.swift
  InFrame/Resources/SceneDelegate.swift
Labels: complete

#72 logInButtonClicked, noAccountButtonClicked 생성
  InFrame/Controllers/LoginViewController.swift
  InFrame/Resources/SceneDelegate.swift
Labels: complete

#73 signUpButtonClicked, haveAccountButtonClicked 추가
  InFrame/Controllers/SignUpViewController.swift
Labels: complete

#74 completeButtonClicked 추가
  InFrame/Controllers/TermsOfServiceViewController.swift
Labels: complete

#75 Feature/terms of service
  InFrame.xcodeproj/project.pbxproj
  InFrame/Assets.xcassets/InFrame_AgreeButtonImage.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_AgreeButtonImage.imageset/aefaefawefaefa.svg
  InFrame/Controllers/AgreeButton.swift
  InFrame/Controllers/TermsOfServiceViewController.swift
Labels: complete, urgent

#77 Feature/main
  InFrame.xcodeproj/project.pbxproj
  InFrame/Assets.xcassets/InFrame_ChoosePicture.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_ChoosePicture.imageset/undraw_Organize_photos_re_ogcy (1).svg
  InFrame/Assets.xcassets/InFrame_TakePicture.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_TakePicture.imageset/undraw_Camera_re_cnp4 (1).svg
  InFrame/Controllers/MainButton.swift
  InFrame/Controllers/MainViewController.swift
  InFrame/Resources/SceneDelegate.swift
Labels: complete
