Repository InFrame-dev/InFrame-iOS, pull requests merged in 2022-06, with the labels that each got.

#113 Feature/camera update
  InFrame.xcodeproj/project.pbxproj
  InFrame/Controllers/ChooseFilterViewController.swift
  InFrame/Controllers/ChooseFrameViewController.swift
  InFrame/Controllers/ChoosePictureViewController.swift
  InFrame/Controllers/MainViewController.swift
  InFrame/Controllers/TakePictureViewController.swift
  InFrame/Resources/APIService.swift
  InFrame/Resources/Base.lproj/LaunchScreen.storyboard
  InFrame/Resources/NetworkResult.swift
Labels: complete, urgent, code-review

#114 Develop
  InFrame.xcodeproj/project.pbxproj
  InFrame/Controllers/ChooseFilterViewController.swift
  InFrame/Controllers/ChooseFrameViewController.swift
  InFrame/Controllers/ChoosePictureViewController.swift
  InFrame/Controllers/FindPasswardEmailViewController.swift
  InFrame/Controllers/GalleryChoosePictureViewController.swift
  InFrame/Controllers/LoginViewController.swift
  InFrame/Controllers/MainButton.swift
  InFrame/Controllers/MainViewController.swift
  InFrame/Controllers/NewPasswordEmailCheckViewController.swift
  InFrame/Controllers/NewPasswordViewController.swift
  InFrame/Controllers/SignUpEmailCheckViewController.swift
  InFrame/Controllers/SignUpViewController.swift
  InFrame/Controllers/TakePictureViewController.swift
  InFrame/Controllers/TermsOfServiceViewController.swift
  InFrame/Extension/Extension.swift
  InFrame/Resources/APIService.swift
  InFrame/Resources/Base.lproj/LaunchScreen.storyboard
  InFrame/Resources/NetworkResult.swift
  InFrame/Views/GradientButton.swift
  InFrame/Views/InputView.swift
  Podfile
  Podfile.lock
Labels: complete, urgent

#118 Hotfix/unused image delete
  InFrame.xcodeproj/project.pbxproj
  InFrame/Assets.xcassets/InFrame_Arrow.imageset/<<<.svg
  InFrame/Assets.xcassets/InFrame_Arrow.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_EmailCheckImage.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_EmailCheckImage.imageset/Group 457.png
  InFrame/Assets.xcassets/InFrame_Eye.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_Eye.imageset/InFrame_Eye.svg
  InFrame/Assets.xcassets/InFrame_EyeNo.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_EyeNo.imageset/EYEYEYEYEYEY.svg
  InFrame/Assets.xcassets/InFrame_FilterBasic.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_FilterBasic.imageset/InFrame_FilterBasic.svg
  InFrame/Assets.xcassets/InFrame_FilterLight.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_FilterLight.imageset/InFrame_FilterLight.svg
  InFrame/Assets.xcassets/InFrame_TestImage.imageset/Contents.json
  InFrame/Assets.xcassets/InFrame_TestImage.imageset/KakaoTalk_Photo_2022-01-03-13-58-23.jpeg
  InFrame/Controllers/ChooseFrameViewController.swift
  InFrame/Views/InputView.swift
Labels: hotfix, complete, urgent

#119 Create LICENSE
  LICENSE
Labels: complete, urgent

#121 [ADD] App Name add
  InFrame/Info.plist
Labels: complete

#123 Hotfix/next to filter
  InFrame/Controllers/ChooseFilterViewController.swift
  InFrame/Controllers/MainViewController.swift
Labels: hotfix, complete, urgent
