Repository InFrame-dev/InFrame-iOS, pull requests merged in 2022-05, with the labels that each got.

#99 [UPDATE] Logo Image png Setting
  InFrame/Assets.xcassets/InFrame_Logo.imageset/1x_InFrame_Logo.png
  InFrame/Assets.xcassets/InFrame_Logo.imageset/2x_InFrame_Logo.png
  InFrame/Assets.xcassets/InFrame_Logo.imageset/3x_InFrame_Logo.png
  InFrame/Assets.xcassets/InFrame_Logo.imageset/Contents.json
  InFrame/Resources/Base.lproj/LaunchScreen.storyboard
Labels: complete

#100 Hotfix/warning
  InFrame/Controllers/ChooseFilterViewController.swift
  InFrame/Controllers/ChooseFrameViewController.swift
  InFrame/Controllers/ChoosePictureViewController.swift
  InFrame/Controllers/FindPasswardEmailViewController.swift
  InFrame/Controllers/LoginViewController.swift
  InFrame/Controllers/MainViewController.swift
  InFrame/Controllers/NewPasswordEmailCheckViewController.swift
  InFrame/Controllers/NewPasswordViewController.swift
  InFrame/Controllers/SignUpEmailCheckViewController.swift
  InFrame/Controllers/SignUpViewController.swift
  InFrame/Controllers/TakePictureViewController.swift
  InFrame/Controllers/TermsOfServiceViewController.swift
  Podfile.lock
Labels: hotfix, complete

#101 Feature/background color modify
  InFrame/Controllers/TakePictureViewController.swift
Labels: complete, code-review

#106 Feature/log in
  InFrame.xcodeproj/project.pbxproj
  InFrame/Controllers/FindPasswardEmailViewController.swift
  InFrame/Controllers/LoginViewController.swift
  InFrame/Controllers/NewPasswordEmailCheckViewController.swift
  InFrame/Controllers/NewPasswordViewController.swift
  InFrame/Controllers/SignUpEmailCheckViewController.swift
  InFrame/Controllers/SignUpViewController.swift
  InFrame/Controllers/TermsOfServiceViewController.swift
Labels: complete, code-review, delete

#108 Feature/log in
  InFrame/Controllers/ChoosePictureViewController.swift
  InFrame/Controllers/GalleryChoosePictureViewController.swift
  InFrame/Controllers/MainButton.swift
  InFrame/Controllers/MainViewController.swift
  InFrame/Extension/Extension.swift
  InFrame/Views/GradientButton.swift
  InFrame/Views/InputView.swift
  Podfile
  Podfile.lock
Labels: complete, code-review

#109 [CREATE] If press Cancel button, selection reset.
  InFrame/Controllers/MainViewController.swift
Labels: complete, code-review
